dist: xenial  # for python >= 3.7
language: python
install:
  - pip install black flake8 mypy mccabe
  - pip install -r requirements.txt
cache: pip
git:
  depth: false
  submodules: false
script:
  - $TEST_CMD
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
matrix:
  include:
    - name: "mypy"
      python: 3.7
      env:
        - TEST_CMD="mypy ."
    - name: "black"
      python: 3.7
      env:
        - TEST_CMD="black --check --verbose ."
    - name: "flake8"
      python: 3.7
      env:
        - TEST_CMD="flake8 ."
    - name: "differences.py"
      python: 3.7
      env:
        - TEST_CMD="python -m xrfp.input.differences"
    - name: "Parse"
      python: 3.7
      env:
        - TEST_CMD="python -m xrfp.input.parse"
    - name: "Structures"
      python: 3.7
      env:
        - TEST_CMD="python -m xrfp.input.structures"
